package com.example.demo2.service;

import com.example.demo2.datatransferobject.TaskResponse;
import com.example.demo2.entity.Task;
import com.example.demo2.exception.TaskNotFoundException;
import com.example.demo2.repository.TaskRepository;
import com.example.demo2.datatransferobject.TaskRequest;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * SERVICE CLASS: TaskService
 * 
 * ========== WHAT IS A SERVICE? ==========
 * A Service is the "BUSINESS LOGIC LAYER" - the middle-man between Controller and Repository.
 * It handles all the complex logic and rules, NOT the HTTP requests.
 * 
 * ========== HOW IT FITS IN THE SYSTEM ==========
 * Request Flow:
 *   Client (Browser/App)
 *      ↓
 *   TaskController (receives HTTP request)
 *      ↓
 *   TaskService (applies business rules and logic) ← YOU ARE HERE
 *      ↓
 *   TaskRepository (talks to the database)
 *      ↓
 *   PostgreSQL Database (stores data)
 * 
 * ========== WHY USE A SERVICE LAYER? ==========
 * 1. SEPARATION OF CONCERNS: Controller focuses on HTTP, Service focuses on business logic
 * 2. REUSABILITY: Multiple controllers can use the same service
 * 3. TESTABILITY: Easy to test business logic separately
 * 4. MAINTAINABILITY: Changes to business logic are in ONE place
 */
@Service
public class TaskService {

    private final TaskRepository taskRepository;

    /**
     * CONSTRUCTOR: Dependency Injection
     * Spring Boot automatically provides taskRepository when creating this service.
     */
    public TaskService(TaskRepository taskRepository) {
        this.taskRepository = taskRepository;
    }

    /**
     * METHOD: getAllTasks()
     * PURPOSE: Fetch all tasks from the database
     * WHEN CALLED: Client sends GET /tasks → Controller calls this → returns list to Controller → Controller sends JSON to client
     *
     * @return List of all tasks from the database
     */
    public List<TaskResponse> getAllTasks() {
        return taskRepository.findAll()
            .stream()
            .map(task -> new TaskResponse(
                task.getId(),
                task.getTitle(),
                task.getDescription(),
                task.getStatus(),
                task.getPriority(),
                task.getDueDate()
            ))
            .toList();
    }   /*why stream and map is use is to convert the list of Task entities from the database into a 
        list of TaskResponse DTOs that we can send back to the client. This is a common practice to separate 
        the internal data model (Task) from the data we expose to the client (TaskResponse).*/

        /*toList is a terminal operation that collects the stream elements into a List. So the final 
        result of this method is a List<TaskResponse> that contains all the tasks from the database 
        in a format suitable for the client.*/
    
    /**
     * METHOD: createTask(Task task)
     * PURPOSE: Create and save a new task to the database
     * WHEN CALLED: Client sends POST /tasks with task data → Controller calls this → saves to database → returns saved task to Controller
     * NOTE: This is where you would add validation logic (check if title is valid, etc.)
     *
     * @param task The task object to save (title and description)
     * @return The saved task with auto-generated ID from the database
     */
    public TaskResponse createTask(TaskRequest request) {
        //return taskRepository.save(task);
        Task task = new Task();
        task.setTitle(request.getTitle());
        task.setDescription(request.getDescription());
        task.setStatus(request.getStatus());
        task.setPriority(request.getPriority());
        task.setDueDate(request.getDueDate());

        Task saved = taskRepository.save(task);
        return new TaskResponse(
            saved.getId(),
            saved.getTitle(),
            saved.getDescription(),
            saved.getStatus(),
            saved.getPriority(),
            saved.getDueDate()
        );
    }
    
    /*explanation of the use of taskrequest and taskresponse in this file is that TaskRequest 
    is used to receive data from the client when creating or updating a task, while TaskResponse 
    is used to send data back to the client after performing operations on the task. 
    This separation allows for better control over the data flow and ensures that the internal 
    representation of the task (Task entity) is not directly exposed to the client, providing a 
    layer of abstraction and security.*/

    public TaskResponse updateTask(Long id, TaskRequest request) {

        Task existingTask = taskRepository.findById(id).orElseThrow(() -> new TaskNotFoundException("Task not found"));
        // Update the existing task with new values using the setter methods generated by Lombok in the Task entity class
        existingTask.setTitle(request.getTitle());
        existingTask.setDescription(request.getDescription());
        existingTask.setStatus(request.getStatus());
        existingTask.setPriority(request.getPriority());
        existingTask.setDueDate(request.getDueDate());

        Task updated = taskRepository.save(existingTask);

        return new TaskResponse(
            updated.getId(),
            updated.getTitle(),
            updated.getDescription(),
            updated.getStatus(),
            updated.getPriority(),
            updated.getDueDate()
        );
    }

    public void deleteTask(Long id) {
        if (!taskRepository.existsById(id)) {
            throw new TaskNotFoundException("Task not found");
        }
        taskRepository.deleteById(id);
    }
}