package com.example.demo2.service;

import com.example.demo2.datatransferobject.TaskResponse;
import com.example.demo2.entity.Task;
import com.example.demo2.exception.TaskNotFoundException;
import com.example.demo2.repository.TaskRepository;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * SERVICE CLASS: TaskService
 * 
 * ========== WHAT IS A SERVICE? ==========
 * A Service is the "BUSINESS LOGIC LAYER" - the middle-man between Controller and Repository.
 * It handles all the complex logic and rules, NOT the HTTP requests.
 * 
 * ========== HOW IT FITS IN THE SYSTEM ==========
 * Request Flow:
 *   Client (Browser/App)
 *      ↓
 *   TaskController (receives HTTP request)
 *      ↓
 *   TaskService (applies business rules and logic) ← YOU ARE HERE
 *      ↓
 *   TaskRepository (talks to the database)
 *      ↓
 *   PostgreSQL Database (stores data)
 * 
 * ========== WHY USE A SERVICE LAYER? ==========
 * 1. SEPARATION OF CONCERNS: Controller focuses on HTTP, Service focuses on business logic
 * 2. REUSABILITY: Multiple controllers can use the same service
 * 3. TESTABILITY: Easy to test business logic separately
 * 4. MAINTAINABILITY: Changes to business logic are in ONE place
 */
@Service
public class TaskService {

    private final TaskRepository taskRepository;

    /**
     * CONSTRUCTOR: Dependency Injection
     * Spring Boot automatically provides taskRepository when creating this service.
     */
    public TaskService(TaskRepository taskRepository) {
        this.taskRepository = taskRepository;
    }

    /**
     * METHOD: getAllTasks()
     * PURPOSE: Fetch all tasks from the database
     * WHEN CALLED: Client sends GET /tasks → Controller calls this → returns list to Controller → Controller sends JSON to client
     *
     * @return List of all tasks from the database
     */
    public List<TaskResponse> getAllTasks() {
        return taskRepository.findAll()
            .stream()
            .map(task -> new TaskResponse(
                task.getId(),
                task.getTitle(),
                task.getDescription(),
                task.getStatus(),
                task.getPriority(),
                task.getDueDate()
            ))
            .toList();
    }   /*why stream and map is use is to convert the list of Task entities from the database into a 
        list of TaskResponse DTOs that we can send back to the client. This is a common practice to separate 
        the internal data model (Task) from the data we expose to the client (TaskResponse).*/

        /*toList is a terminal operation that collects the stream elements into a List. So the final 
        result of this method is a List<TaskResponse> that contains all the tasks from the database 
        in a format suitable for the client.*/
    
    /**
     * METHOD: createTask(Task task)
     * PURPOSE: Create and save a new task to the database
     * WHEN CALLED: Client sends POST /tasks with task data → Controller calls this → saves to database → returns saved task to Controller
     * NOTE: This is where you would add validation logic (check if title is valid, etc.)
     *
     * @param task The task object to save (title and description)
     * @return The saved task with auto-generated ID from the database
     */
    public Task createTask(Task task) {
        return taskRepository.save(task);
    }

    public Task updateTask(Long id, Task updatedTask) {

        Task existingTask = taskRepository.findById(id).orElseThrow(() -> new TaskNotFoundException("Task not found"));
        // Update the existing task with new values using the setter methods generated by Lombok in the Task entity class
        existingTask.setTitle(updatedTask.getTitle());
        existingTask.setDescription(updatedTask.getDescription());
        existingTask.setStatus(updatedTask.getStatus());
        existingTask.setPriority(updatedTask.getPriority());
        existingTask.setDueDate(updatedTask.getDueDate());

        return taskRepository.save(existingTask); //uses save created
    }

    public void deleteTask(Long id) {
        if (!taskRepository.existsById(id)) {
            throw new TaskNotFoundException("Task not found");
        }
        taskRepository.deleteById(id);
    }
}